# 工作流名称
name: Build and Publish Docker Image

# 当推送tag时触发执行
on:
  push:
    tags:
      - v*

# 定义环境变量，后面会使用
env:
  APP_NAME: stocks_all  # 替换为你的应用名称
  DOCKERHUB_REPO: idcims/stocks_all  # 替换为你的Docker Hub用户名和镜像名称

jobs:
  main:
    # 在 Ubuntu 上运行
    runs-on: ubuntu-latest
    steps:
      # git checkout 代码
      - name: Checkout
        uses: actions/checkout@v2

      # 登录 docker hub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          # GitHub Repo => Settings => Secrets 增加 docker hub 登录密钥信息
          # DOCKERHUB_USERNAME 是 docker hub 账号名
          # DOCKERHUB_TOKEN: docker hub => Account Setting => Security 创建
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 通过 git 命令获取当前 tag 信息，存入环境变量 APP_VERSION
      - name: Generate Version
        run: echo APP_VERSION=$(git describe --tags --always) >> $GITHUB_ENV

      # 构建 Docker 并推送到 Docker hub
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # 是否 docker push
          push: true
          # 构建上下文目录
          context: .
          # Dockerfile 路径
          file: ./Dockerfile
          # docker build arg, 注入 APP_NAME/APP_VERSION
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.APP_VERSION }}
          # 生成两个 docker tag: ${APP_VERSION} 和 latest
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}
            ${{ env.DOCKERHUB_REPO }}:latest
